version: '3.7'
  
services:
    jenkins:
        container_name: jenkins
        image: jenkins/jenkins:lts
        volumes:
            - ./data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 7000:8080
        privileged: true
        user: root